---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: _data/shop.yaml
  label: Product List
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - blog-post
- type: jekyll-pages
  label: Pages
  create: documents
  templates:
  - page
- type: heading
  label: Products
- type: heading
  label: Bear Pride
- type: document
  path: _data/events.yaml
  label: Events
- type: document
  path: _data/candidates.yaml
  label: Candidates
- type: document
  path: _data/sponsors.yaml
  label: Sponsors
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:/:month:/:day:-:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
